osx_image: xcode9.2
language: objective-c
jobs:
  include:
    - stage: testing
      before_install:
        - gem install cocoapods
      script: 
        - cd Example
        - pod install
        - xcodebuild test -workspace SwiftCommonUtils.xcworkspace -scheme SwiftCommonUtils-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' -quiet
    - stage: deploy to cocoapods
      env:
        - SWIFTCOMMONUTILS_VERSION=$TRAVIS_TAG
      before_install:
        - gem install cocoapods
      script:
        - pod lib lint --allow-warnings
        - pod trunk push
      if: tag IS present